### ISSUE TITLE
Contain text overflow in table 

### ISSUE THREAD

**Issue by BrianLitwin** [BrianLitwin/GoodFirstIssue#3]
In the table, Repositories have an 'expand' button beside them and Issues have the Issue number link. When text overflows, it wraps under those elements, instead of starting where the text starts on the top line, ie, beside the expand button or issue number link.

**Comment by BrianLitwin** [comment]
make buttons their own td's

**Comment by tsmrachel** [comment]
any particular reason to use td for the button? A float left works without further adjustment of the td sizing

td
![image](https://user-images.githubusercontent.com/3946307/53681459-ee70d600-3d24-11e9-8bf3-dde4815e8b7b.png)

float : left

![image](https://user-images.githubusercontent.com/3946307/53681464-fdf01f00-3d24-11e9-9f9d-db7bc6fa48d4.png)

with flex for the issue row

![image](https://user-images.githubusercontent.com/3946307/53681541-32b0a600-3d26-11e9-8a0d-c1e020351bb7.png)

**Comment by BrianLitwin** [comment]
@tsmrachel You're right; could you post that code or submit a PR? I want exactly what you've posted in the screenshot but can't get float or flex to work as intended.

**Comment by tsmrachel** [comment]
if the code is okay let me know, will resolve the conflicts so you can merge
